/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114525-gba7980d9c0-20240330"
#endif /* AVUTIL_FFVERSION_H */
